import dotenv from "dotenv";
dotenv.config();

const TEST_CONSTANTS = {
  APP_BASE_URL: process.env.APP_BASE_URL || "https://dev.coach.uprio.com",
  API_BASE_URL: process.env.API_BASE_URL || "https://dev.backend.uprio.com",
  UPRIO_URL: process.env.UPRIO_URL || "https://dev.uprio.com",
  X_API_KEY: process.env.X_API_KEY || "",
  TEST_USER_REGISTERED_NUMBER_FOR_NON_OTP_TEST:
    process.env.TEST_USER_REGISTERED_NUMBER_FOR_NON_OTP_TEST || "",
  TEST_USER_PASSCODE_FOR_NON_OTP_TEST:
    process.env.TEST_USER_PASSCODE_FOR_NON_OTP_TEST || "1234",
  TEST_USER_REGISTERED_NUMBER_FOR_OTP_TEST:
    process.env.TEST_USER_REGISTERED_NUMBER_FOR_OTP_TEST || "",
  TEST_USER_UNREGISTERED_NUMBER:
    process.env.TEST_USER_UNREGISTERED_NUMBER || "",
  TEST_USER_LANDING_PAGE_NUMBER:
    process.env.TEST_USER_LANDING_PAGE_NUMBER || "",
  TEST_USER_REGISTERED_EMAIL_FOR_OTP_TEST:
    process.env.TEST_USER_REGISTERED_EMAIL_FOR_OTP_TEST || "",
  TEST_USER_PAYMENTS_NUMBER: process.env.TEST_USER_PAYMENTS_NUMBER || "",
  TEST_USER_DEMO_BOOKING_NUMBER:
    process.env.TEST_USER_DEMO_BOOKING_NUMBER || "",
  TEST_USER_INVALID_NUMBER: process.env.TEST_USER_INVALID_NUMBER || "7259",
  APP_ADMIN_URL: process.env.APP_ADMIN_URL || "https://dev.admin.uprio.com",
  APP_LIGHTHOUSE_URL:
    process.env.APP_LIGHTHOUSE_URL || "https://dev.lighthouse.uprio.com",
  TEST_TUTOR_EMAIL: process.env.TEST_TUTOR_EMAIL || "",
  TEST_TUTOR_PASSWORD: process.env.TEST_TUTOR_PASSWORD || "",
  TEST_STUDENT_FOR_INCLASS_NUMBER:
    process.env.TEST_STUDENT_FOR_INCLASS_NUMBER || "",
  TEST_STUDENT_FOR_INCLASS_PASSCODE:
    process.env.TEST_STUDENT_FOR_INCLASS_PASSCODE || "1234",
  TEST_STUDENT_INTERVENTION_NUMBER:
    process.env.TEST_STUDENT_INTERVENTION_NUMBER || "",
  TEST_STUDENT_INTERVENTION_PASSCODE:
    process.env.TEST_STUDENT_INTERVENTION_PASSCODE || "0644",
  TEST_TUTOR_KEY: process.env.TUTOR_AUTHENTICATOR_KEY || "",
  TEST_ADMIN_KEY: process.env.SUPERADMIN_AUTHENTICATOR_KEY || "",
  TEST_ADMIN_EMAIL: process.env.TEST_ADMIN_EMAIL || "",
  TEST_ADMIN_PASSWORD: process.env.TEST_ADMIN_PASSWORD || "",
  TEST_STUDENT_FOR_ADMIN_TEST_CASES_NUMBER:
    process.env.TEST_STUDENT_FOR_ADMIN_TEST_CASES_NUMBER,
  LEAD_CREATION_STUDENT_MOBILE_NUMBER:
    process.env.LEAD_CREATION_STUDENT_MOBILE_NUMBER || "",
  SETUP_SCREEN_VERSION: process.env.SETUP_SCREEN_VERSION || "",
};

export default { TEST_CONSTANTS };
